### ISSUE TITLE
Add isort to pre-commit hooks

### ISSUE THREAD

**Issue by klamann** [at-gmbh/at-python-template#71]
We should use a consistent style for import statements. Proposed config:

```
repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: ['--py', '38', '--line-length', '100', '--multi-line', '3']
```
